[PHP]
; --- Ошибки ---
display_errors = On
display_startup_errors = On
error_reporting = E_ALL

; --- Ресурсы ---
memory_limit = 512M
post_max_size = 1024M
upload_max_filesize = 1024M
max_execution_time = 300

; --- Расширения ---
; Указываем путь к папке ext относительно самого php.exe
extension_dir = "ext"

; Включаем ZIP (пробуем оба варианта написания для надежности)
extension=zip
extension=php_zip.dll

; Другие полезные расширения
extension=curl
extension=mbstring
extension=fileinfo
extension=gd